### ISSUE TITLE
好像不是很明白，如何区分客户端和服务端

### ISSUE THREAD

**Issue by ChenZIDu** [rocketk/revproxy#1]

**Comment by rocketk** [comment]
这个程序主要是用来做反向代理的，如果你用过nginx的话，那么就很容易理解。
>如何区分客户端和服务端

这个问题我没太明白问的是什么，是看到这个配置文件感到疑惑吗？
```yaml
target:
  base-url: http://example.com/
  prefix-to-trim: 
server:
  port: 9080
```


server.port 就是本程序自己占用的端口；

target.base-url 就是要访问的目标服务地址，在nginx里就是upstream
